export const INIT = 'INIT'
export const INIT_PRIVATE = 'INIT_PRIVATE'
export const CREATE = 'CREATE'
export const CREATE_PRIVATE = 'CREATE_PRIVATE'
export const UPDATE = 'UPDATE'
export const INCREASE = 'INCREASE'
export const ENTER = 'ENTER'
