export const SET_TEXT = 'SET_TEXT'
export const SET_IMAGE = 'SET_IMAGE'
export const SET_TAG = 'SET_TAG'
export const CLEAR = 'CLEAR'
export const POST = 'POST'
export const POST_TEXT = 'POST_TEXT'
export const POST_IMAGE = 'POST_IMAGE'
export const INCREASE = 'INCREASE'
