export const SET_MESSAGE = 'SET_MESSAGE'
export const INIT = 'INIT'
export const LOAD_MORE = 'LOAD_MORE'
export const SET_LAST_VISIBLE = 'SET_LAST_VISIBLE'
export const LOADING = 'LOADING'
export const END_OF_RECORD = 'END_OF_RECORD'
